import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "../globals.css";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { headers } from "next/headers";
import { Suspense } from "react";
import DLayout from "./dashboard/DLayout";

const k2d = K2D({
    subsets: ['thai'],
    weight: ['100', '400', '500', '800'],
    display: 'swap'
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

// แยกส่วนที่เป็น dynamic ออกมา ให้ render ภายใต้ Suspense
async function AdminGuard({ children }: { children: React.ReactNode }) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (session?.user.role !== 'admin') {
    redirect('/');
  }

  return <>{children}</>;
}


export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
      className={`${k2d.className}`}
    >
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <AdminGuard>
            <DLayout>
              {children}
            </DLayout>
          </AdminGuard>
        </Suspense>
      </body>
    </html>
  );
}
