import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "../globals.css";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { headers } from "next/headers";

const k2d = K2D({
    subsets: ['thai'],
    weight: ['100', '400', '500', '800'],
    display: 'swap'
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth.api.getSession({
    headers: await headers()
  });
  if (session?.user.role !== 'admin') {
    redirect('/');
  }  

  return (
    <html
      lang="th"
      className={`${k2d.className}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
