import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import { Suspense } from "react";

export const promptFont = Prompt({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap"
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME ?? 'Next.js App',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
    >
      <body className={promptFont.className}>
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
